const eventsData = [
    {
        id: 1,
        name: "Parting of the Red Sea",
        description: "Moses parted the sea to escape Pharaoh’s army.",
        fullDescription: "God miraculously parted the Red Sea, allowing the Israelites to escape Egypt, then closed it on their pursuers.",
        image: "https://www.rainbowtoken.com/wp-content/uploads/2017/09/Exodus-14-15-31-Parting-the-Red-Sea.jpg",
        time_period: "1400 BC",
        testament: "old",
        category: "events",
        related_figures: ["Moses"],
        related_locations: ["Egypt", "Red Sea"],
        scripture_references: ["Exodus 14"],
        historical_context: "Escape from Egyptian bondage.",
        significance: "Demonstration of God's power and deliverance.",
        typeofevent: "Miracle"
    },
    {
        id: 2,
        name: "Crucifixion of Jesus",
        description: "Jesus died on the cross.",
        fullDescription: "Pivotal event where Jesus was crucified, fulfilling prophecy and atoning for humanity's sins.",
        image: "https://i.guim.co.uk/img/media/f1696eece1e8baeb6ff15f9f181cb378ffae2844/1504_631_2868_1721/master/2868.jpg?width=480&dpr=1&s=none&crop=none",
        time_period: "30 AD",
        testament: "new",
        category: "events",
        related_figures: ["Jesus Christ", "Mary"],
        related_locations: ["Jerusalem"],
        scripture_references: ["Matthew 27", "Mark 15", "Luke 23", "John 19"],
        historical_context: "Under Roman governor Pontius Pilate.",
        significance: "Central to Christian salvation.",
        typeofevent: "Salvation"
    },
    {
        id: 3,
        name: "Noah's Flood",
        description: "Great flood that covered the earth.",
        fullDescription: "God sent a worldwide flood to destroy the wicked, preserving Noah and his family in the ark.",
        image: "https://cdn.mos.cms.futurecdn.net/NqeaQsAQMPCr2viN3M6uGk.jpg",
        time_period: "2500 BC",
        testament: "old",
        category: "events",
        related_figures: ["Noah"],
        related_locations: ["Ararat"],
        scripture_references: ["Genesis 6-9"],
        historical_context: "Prehistoric judgment on humanity.",
        significance: "God's judgment and promise of renewal.",
        typeofevent: "Judgment"
    },
    {
        id: 4,
        name: "Resurrection",
        description: "Jesus rose from the dead.",
        fullDescription: "Three days after crucifixion, Jesus rose, proving his divinity and victory over death.",
        image: "https://www.bookofmormoncentral.org/sites/default/files/pictures/page-images/blog-entry/2019/friberg-christ-america-resurrection-book-of-mormon.jpg",
        time_period: "30 AD",
        testament: "new",
        category: "events",
        related_figures: ["Jesus Christ"],
        related_locations: ["Jerusalem"],
        scripture_references: ["Matthew 28", "Mark 16", "Luke 24", "John 20"],
        historical_context: "Post-crucifixion, early Christian era.",
        significance: "Cornerstone of Christian hope.",
        typeofevent: "Salvation"
    },
    {
        id: 5,
        name: "David vs. Goliath",
        description: "David defeated the giant Goliath.",
        fullDescription: "Young David defeated the Philistine giant with a sling and stone, showing God's favor.",
        image: "https://img1.wsimg.com/isteam/ip/c787bd1f-ee40-4810-83a2-7cea1301bd7a/david-and-goliath.jpg",
        time_period: "1000 BC",
        testament: "old",
        category: "events",
        related_figures: ["David"],
        related_locations: ["Valley of Elah"],
        scripture_references: ["1 Samuel 17"],
        historical_context: "Israel-Philistine conflict.",
        significance: "Victory through faith in God.",
        typeofevent: "Battle"
    },
    {
        id: 6,
        name: "Creation",
        description: "God created the world.",
        fullDescription: "In six days, God created the heavens, earth, and all living things, resting on the seventh.",
        image: "https://miro.medium.com/v2/resize:fit:981/0*GlTVNHK8Oc867E3Y.jpeg",
        time_period: "Beginning",
        testament: "old",
        category: "events",
        related_figures: ["Adam","Eve","God"],
        related_locations: ["Garden of Eden"],
        scripture_references: ["Genesis 1-2"],
        historical_context: "Origin of existence.",
        significance: "Foundation of biblical cosmology.",
        typeofevent: "Creation"
    },
    {
        id: 7,
        name: "Birth of Jesus",
        description: "Jesus was born in Bethlehem.",
        fullDescription: "Born to Mary in a manger, heralded by angels and visited by shepherds and wise men.",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Adoration_of_the_sheperds_-_Matthias_Stomer.jpg",
        time_period: "4 BC",
        testament: "new",
        category: "events",
        related_figures: ["Jesus Christ", "Mary", "Joseph"],
        related_locations: ["Bethlehem"],
        scripture_references: ["Luke 2", "Matthew 2"],
        historical_context: "During Herod the Great's reign.",
        significance: "Incarnation of God as man.",
        typeofevent: "Birth"
    },
    {
        id: 8,
        name: "Pentecost",
        description: "Holy Spirit descended on the apostles.",
        fullDescription: "After Jesus' ascension, the Holy Spirit empowered the apostles to speak in tongues.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Vienna_Karlskirche_frescos4b.jpg",
        time_period: "30 AD",
        testament: "new",
        category: "events",
        related_figures: ["Peter", "Jesus Christ"],
        related_locations: ["Jerusalem"],
        scripture_references: ["Acts 2"],
        historical_context: "Birth of the Christian church.",
        significance: "Empowerment of the early church.",
        typeofevent: "Spiritual Empowerment"
    },
    {
        id: 9,
        name: "Fall of Jericho",
        description: "Walls of Jericho fell.",
        fullDescription: "Joshua led the Israelites to march around Jericho, and God caused the walls to collapse.",
        image: "https://www.ellenwhite.info/images/chapt-illus/PP/RH-FallOfJericho3.jpg",
        time_period: "1400 BC",
        testament: "old",
        category: "events",
        related_figures: ["Joshua"],
        related_locations: ["Jericho"],
        scripture_references: ["Joshua 6"],
        historical_context: "Conquest of Canaan.",
        significance: "God's miraculous intervention.",
        typeofevent: "Miracle"
    },
    {
        id: 10,
        name: "Covenant with God",
        description: "God made a covenant with Abraham.",
        fullDescription: "God promised Abraham land and descendants, sealed with circumcision.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Double-alaskan-rainbow.jpg/1200px-Double-alaskan-rainbow.jpg",
        time_period: "2000 BC",
        testament: "old",
        category: "events",
        related_figures: ["Abraham"],
        related_locations: ["Canaan"],
        scripture_references: ["Genesis 15-17"],
        historical_context: "Early patriarchal period.",
        significance: "Basis of Israelite identity.",
        typeofevent: "Covenant"
    }
];