const locationsData = [
    {
        id: 1,
        name: "Mount Sinai",
        description: "Where Moses received the Ten Commandments.",
        fullDescription: "Mountain where God gave Moses the Ten Commandments, establishing the covenant with Israel.",
        image: "https://media.swncdn.com/via/20987-gettyimages-523617777.jpg",
        time_period: "1400 BC",
        testament: "old",
        importance: false,
        category: "locations",
        related_figures: ["Moses"],
        related_events: ["Parting of the Red Sea", "Receiving the Ten Commandments"],
        scripture_references: ["Exodus 19-20"],
        historical_context: "Post-Exodus wilderness period.",
        significance: "Site of divine revelation."
    },
    {
        id: 2,
        name: "Jerusalem",
        description: "Holy city in both testaments.",
        fullDescription: "Central city of biblical history, home to the Temple, and site of Jesus' ministry and crucifixion.",
        image: "https://wol.jw.org/en/wol/mp/r1/lp-e/it-1/2018/402",
        time_period: "1000 BC - 30 AD",
        testament: "both",
        importance: true,
        category: "locations",
        related_figures: ["David", "Jesus Christ", "Solomon"],
        related_events: ["Crucifixion of Jesus", "Resurrection", "Establishment of Jerusalem"],
        scripture_references: ["2 Samuel 5", "Matthew 27", "Acts 2"],
        historical_context: "Capital of Israel and Judea.",
        significance: "Spiritual and political center."
    },
    {
        id: 3,
        name: "Bethlehem",
        description: "Birthplace of Jesus.",
        fullDescription: "Small town where Jesus was born, fulfilling prophecy as the city of David.",
        image: "https://www.jesus-story.net/wp-content/uploads/2019/01/Houses_Native_village.jpg",
        time_period: "4 BC",
        testament: "new",
        importance: true,
        category: "locations",
        related_figures: ["Jesus Christ", "Mary", "David"],
        related_events: ["Birth of Jesus"],
        scripture_references: ["Micah 5:2", "Luke 2"],
        historical_context: "Roman-era Judea.",
        significance: "Messianic prophecy fulfilled."
    },
    {
        id: 4,
        name: "Egypt",
        description: "Land of Israelite slavery.",
        fullDescription: "Where the Israelites were enslaved before the Exodus, ruled by Pharaoh.",
        image: "https://images.theconversation.com/files/396859/original/file-20210423-13-7dpil7.jpg?ixlib=rb-4.1.0&rect=0%2C109%2C1585%2C792&q=45&auto=format&w=1356&h=668&fit=crop",
        time_period: "1400 BC",
        testament: "old",
        importance: true,
        category: "locations",
        related_figures: ["Moses", "Joseph"],
        related_events: ["Parting of the Red Sea", "Joseph's Rise to Power"],
        scripture_references: ["Exodus 1-15", "Genesis 39-50"],
        historical_context: "New Kingdom period of Egypt.",
        significance: "Setting for Israel's formation."
    },
    {
        id: 5,
        name: "Canaan",
        description: "Promised Land.",
        fullDescription: "Land promised to Abraham's descendants, conquered by Joshua after the Exodus.",
        image: "https://cdn.prod.website-files.com/5b8fd783bee52c8fb59b1fac/651d85eb1c55b7f3d1d60206_Viewing%2520the%2520Promised%2520Land%252C%2520Moses%2520Looks%2520Even%2520at%2520the%2520Transjordan.jpeg",
        time_period: "1400 BC",
        testament: "old",
        importance: true,
        category: "locations",
        related_figures: ["Abraham", "Joshua"],
        related_events: ["Conquest of Canaan", "Covenant with God"],
        scripture_references: ["Genesis 12", "Joshua"],
        historical_context: "Late Bronze Age.",
        significance: "Fulfillment of divine promise."
    },
    {
        id: 6,
        name: "Galilee",
        description: "Region of Jesus' ministry.",
        fullDescription: "Northern region of Israel where Jesus performed many miracles and taught.",
        image: "https://cbnisrael.org/wp-content/uploads/2021/11/2021-11-16-Galilee-Marc-Turnage-958x653.jpg",
        time_period: "4 BC - 30 AD",
        testament: "new",
        importance: false,
        category: "locations",
        related_figures: ["Jesus Christ", "Peter"],
        related_events: ["Ministry of Jesus"],
        scripture_references: ["Matthew 4", "Mark 1"],
        historical_context: "Roman province of Judea.",
        significance: "Center of Jesus' teachings."
    },
    {
        id: 7,
        name: "Damascus",
        description: "Site of Paul's conversion.",
        fullDescription: "Ancient city where Paul encountered Jesus on the road, leading to his conversion.",
        image: "https://via.placeholder.com/250x150?text=Damascus",
        time_period: "5 AD - 67 AD",
        testament: "new",
        importance: false,
        category: "locations",
        related_figures: ["Paul"],
        related_events: ["Conversion of Paul"],
        scripture_references: ["Acts 9"],
        historical_context: "Roman Syria.",
        significance: "Turning point in Christian expansion."
    },
    {
        id: 8,
        name: "Jericho",
        description: "City conquered by Joshua.",
        fullDescription: "Ancient city whose walls fell after the Israelites marched around it.",
        image: "https://via.placeholder.com/250x150?text=Jericho",
        time_period: "1400 BC",
        testament: "old",
        importance: true,
        category: "locations",
        related_figures: ["Joshua"],
        related_events: ["Fall of Jericho"],
        scripture_references: ["Joshua 6"],
        historical_context: "Entry into Canaan.",
        significance: "First victory in the Promised Land."
    },
    {
        id: 9,
        name: "Rome",
        description: "Center of Paul's later ministry.",
        fullDescription: "Capital of the Roman Empire where Paul preached and was eventually martyred.",
        image: "https://via.placeholder.com/250x150?text=Rome",
        time_period: "5 AD - 67 AD",
        testament: "new",
        importance: true,
        category: "locations",
        related_figures: ["Paul"],
        related_events: ["Missionary Journeys"],
        scripture_references: ["Acts 28", "Romans"],
        historical_context: "Height of Roman Empire.",
        significance: "Spread of Christianity to the Gentile world."
    },
    {
        id: 10,
        name: "Ararat",
        description: "Resting place of Noah's Ark.",
        fullDescription: "Mountain range where the ark came to rest after the flood.",
        image: "https://via.placeholder.com/250x150?text=Ararat",
        time_period: "2500 BC",
        testament: "old",
        importance: false,
        category: "locations",
        related_figures: ["Noah"],
        related_events: ["Noah's Flood"],
        scripture_references: ["Genesis 8"],
        historical_context: "Post-flood era.",
        significance: "Symbol of God's new beginning."
    },
    // ... Add remaining 7 locations as needed ...
];